
class AssertionError(Exception):
    pass

class SatisfactionError(AssertionError):
    pass
